### ISSUE TITLE
voicevox-previewとvoicevox-devの名前変更

### ISSUE THREAD

**Issue by nix6839** [VOICEVOX/homebrew-voicevox#44]
## 内容
[公式のhomebrew-cask レポジトリ](https://github.com/Homebrew/homebrew-cask)では、追加的なバージョン(preview, dev, nigthly など)に対して区切り文字として`@`を付けるようです。 それに合わせて私たちも`-`の代わりに`@`を使うのはどうでしょうか？

参考Caskら:
- [gimp@dev](https://github.com/Homebrew/homebrew-cask/blob/6819233c74405ba3386e96b293e4d58c3bd0f960/Casks/g/gimp%40dev.rb)
- [zed@preview](https://github.com/Homebrew/homebrew-cask/blob/6819233c74405ba3386e96b293e4d58c3bd0f960/Casks/z/zed%40preview.rb)
- [visual-studio-code@insiders](https://github.com/Homebrew/homebrew-cask/blob/6819233c74405ba3386e96b293e4d58c3bd0f960/Casks/v/visual-studio-code%40insiders.rb)

### Pros 良くなる点
- 公式レポジトリとの差を縮めることができます。
	- 後でこのCaskを公式レポジトリにアップロードする時、変更事項を減らすことができます。
	- ユーザが公式レポジットリと同様の方法でこのtabを利用することができます。

### Cons 悪くなる点
~~既存のユーザーが混乱する可能性があります。(この部分はtabにも適用されるかどうかは分かりませんが、おそらく[`cask_renames.json`](https://github.com/Homebrew/homebrew-cask/blob/master/cask_renames.json)ファイルで混乱を減らすことができると思います。)~~
既存のユーザーが混乱する可能性があります。(この部分は[`cask_renames.json`](https://github.com/Homebrew/homebrew-cask/blob/master/cask_renames.json)ファイルで混乱を減らすことができます。)

### 実現方法
- 名前を変更します。
- `cask_renames.json`ファイルを追加します。

**Comment by nix6839** [comment]
私のフォークされたレポジトリで確認した結果、`cask_renames.json`が正常に動作します。

**Comment by Hiroshiba** [comment]
@nix6839 良いと思います！もしよかったらプルリクエストをいただけますか？
